language: elixir
sudo: false
elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.0
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
script: mix test
after_script:
  - mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
