language: elixir
sudo: false
elixir:
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 20.0
  - 21.0
  - 22.0
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
script: mix test
after_script:
  - mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
